# Generated by Django 4.1.3 on 2022-11-30 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(message='Номер телефона клиента в формате 7XXXXXXXXXX', regex='^7\\w{10}$')], verbose_name='Номер телефона')),
                ('phone_code', models.PositiveIntegerField(verbose_name='Код мобильного оператора')),
                ('tag', models.CharField(blank=True, max_length=50, verbose_name='Тeг')),
                ('time_zone', models.CharField(max_length=10, verbose_name='Часовой пояс')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
